name: Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Bring code into the virtual machine
        uses: actions/checkout@v4
      - name: Install nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run the lint scripts
        run: npm run lint
      